name: Deploy React Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Atlas and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa boskyle@froggie.ca<< 'EOF'
            cd /home/boskyle/webdev/react/bloxlore-cms
            git fetch origin
            git checkout staging
            git reset --hard origin/staging
            git clean -fd
            bash run-staging.sh
          EOF
